package device

import (
	"context"

	"github.com/anggi-susanto/mrt-go/domain"
)

// DeviceRepositoryInterface is an autogenerated interface for deviceRepository

type DeviceRepositoryInterface interface {
	Create(ctx context.Context, w *domain.DeviceRequest) error
	GetAll(ctx context.Context, page, limit int) ([]domain.Device, error)
	GetByID(ctx context.Context, id string) (*domain.Device, error)
	Update(ctx context.Context, w *domain.Device) error
	Delete(ctx context.Context, id string) error
}

// Service is the interface that wraps the Create, GetAll, GetByID, Update, and Delete methods.
type Service struct {
	deviceRepository DeviceRepositoryInterface
}

// NewService creates a new instance of the Service struct, initializing it with the provided DeviceRepositoryInterface.
//
// Parameters:
// - deviceRepository: The DeviceRepositoryInterface implementation used by the Service.
//
// Returns:
// - A pointer to the newly created Service instance.
func NewService(deviceRepository DeviceRepositoryInterface) *Service {
	return &Service{
		deviceRepository: deviceRepository,
	}
}

// Create creates a new waste water data record in the service.
//
// ctx: The context.Context object for the request.
// w: The waste water data to be created.
// Returns an error if there was a problem creating the record.
func (s *Service) Create(ctx context.Context, w *domain.DeviceRequest) error {
	return s.deviceRepository.Create(ctx, w)
}

// GetAll retrieves all waste water data with pagination.
//
// ctx context.Context, page int, limit int
// []domain.DeviceData, error
func (s *Service) GetAll(ctx context.Context, page, limit int) ([]domain.Device, error) {
	return s.deviceRepository.GetAll(ctx, page, limit)
}

// GetByID retrieves a DeviceData by ID.
//
// ctx - context.Context for the operation.
// id - string representing the ID of the data.
// Returns a pointer to domain.DeviceData and an error.
func (s *Service) GetByID(ctx context.Context, id string) (*domain.Device, error) {
	return s.deviceRepository.GetByID(ctx, id)
}

// Delete deletes a DeviceData by ID.
//
// ctx - context.Context for the operation.
// id - string representing the ID of the data to be deleted.
// Returns an error if there was a problem deleting the data.
func (s *Service) Delete(ctx context.Context, id string) error {
	return s.deviceRepository.Delete(ctx, id)
}

// Update updates a DeviceData.
//
// ctx - context.Context for the operation.
// w - pointer to domain.DeviceData representing the data to be updated.
// Returns an error if there was a problem updating the data.
func (s *Service) Update(ctx context.Context, w *domain.Device) error {
	return s.deviceRepository.Update(ctx, w)
}
